name: e_kinerja_web_mobile
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.9.2'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.3
  shared_preferences: ^2.3.2
  go_router: ^14.0.1
  intl: ^0.18.0
  fl_chart: ^0.70.0
  excel: ^2.1.0
  path_provider: ^2.0.14
  month_picker_dialog: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
